"""add categorization fields

Revision ID: 479f64e97a2f
Revises: 006
Create Date: 2026-04-13 11:27:51.936609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479f64e97a2f'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_merchant_mappings_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_merchant_mappings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_mappings'))
    )
    op.create_table('category_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=False),
    sa.Column('cleaned_merchant', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('predicted_category_id', sa.UUID(), nullable=True),
    sa.Column('corrected_category_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_category_id'], ['categories.id'], name=op.f('fk_category_corrections_corrected_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predicted_category_id'], ['categories.id'], name=op.f('fk_category_corrections_predicted_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_category_corrections_transaction_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_category_corrections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_corrections'))
    )
    op.add_column('categories', sa.Column('color', sa.String(length=7), server_default='#6B7280', nullable=False))
    op.add_column('transactions', sa.Column('categorization_method', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('is_manually_corrected', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('uq_transactions_account_entry_ref'), table_name='transactions', postgresql_where='(entry_reference IS NOT NULL)')
    op.drop_index(op.f('ix_email'), table_name='users')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('uq_transactions_account_entry_ref'), 'transactions', ['account_id', 'entry_reference'], unique=True, postgresql_where='(entry_reference IS NOT NULL)')
    op.drop_column('transactions', 'is_manually_corrected')
    op.drop_column('transactions', 'confidence_score')
    op.drop_column('transactions', 'categorization_method')
    op.drop_column('categories', 'color')
    op.drop_table('category_corrections')
    op.drop_table('merchant_mappings')
    # ### end Alembic commands ###
