"""add_recurring_charges

Revision ID: ba4c21f3d2d9
Revises: 008
Create Date: 2026-04-16 08:50:51.776970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4c21f3d2d9'
down_revision: Union[str, None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_charges',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('periodicity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='possible', nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('next_predicted_date', sa.Date(), nullable=False),
    sa.Column('last_seen_date', sa.Date(), nullable=False),
    sa.Column('is_installment', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('installment_total', sa.Integer(), nullable=True),
    sa.Column('installment_paid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recurring_charges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_charges')),
    sa.UniqueConstraint('user_id', 'merchant_key', name='uq_recurring_charges_user_merchant')
    )
    op.create_index(op.f('ix_recurring_charges_user_id'), 'recurring_charges', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_charges_user_id'), table_name='recurring_charges')
    op.drop_table('recurring_charges')
    # ### end Alembic commands ###
